spring:
  #数据源配置
  datasource:
    druid:
      db1:
        url: jdbc:mysql://172.31.140.203:3306/bme_prod?characterEncoding=utf-8&useSSL=false&autoReconnect=true&serverTimezone=CTT
        #        url: jdbc:mysql://192.168.1.243:3306/bme_prod?characterEncoding=utf-8&useSSL=false&autoReconnect=true
        username: bme
        password: Bme@709394
        #本机
        #url: jdbc:mysql://127.0.0.1:3306/bme_dev?characterEncoding=utf-8&useSSL=false&autoReconnect=true
        #username: root
        #password: 1q2w3e4r
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
        type: com.alibaba.druid.pool.DruidDataSource

        #   druid数据源其他配置,无法通过DataSourceProperties注入
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,logback
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      db2:
        url: jdbc:sqlserver://47.105.46.104:1433;Databasename=BME_Test
        username: bme
        password: bme@12345
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        initialSize: 5
        minIdle: 5
        maxActive: 20
      db3:
        url: jdbc:mysql://172.31.140.206:4000/bme_prod?characterEncoding=utf-8&useSSL=false&autoReconnect=true&serverTimezone=CTT
        #        url: jdbc:mysql://192.168.1.246:4000/bme_prod?characterEncoding=utf-8&useSSL=false&autoReconnect=true
        username: root
        password: bme@123
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
